name: Testing react app
on: push
jobs:
  test_my_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install deps
        run : npm ci
      - name: Test app
        run : npm run test